server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: 2546125461
  jpa:
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://pejenpkz:qfLDQb3S1txjQpw6HDrd-K3FQqRdiW5J@woodpecker.rmq.cloudamqp.com/pejenpkz

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser/'

eureka:
  client:
    serviceUrl:
      defaultZone:  'http://localhost:8761/eureka'
  instance:
    hostname: localhost