server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: 2546125461
  jpa:
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://pejenpkz:qfLDQb3S1txjQpw6HDrd-K3FQqRdiW5J@woodpecker.rmq.cloudamqp.com/pejenpkz

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser/'
  broker:
    exchange:
      userEventExchange:  ead.userevent
      notificationCommandExchange:  ead.notificationcommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification

eureka:
  client:
    serviceUrl:
      defaultZone:  'http://localhost:8761/eureka'
  instance:
    hostname: localhost